language: node_js
node_js:
  - "7"
  - "6"

dist: trusty
sudo: required

addons:
  srcclr:
    debug: true
  sonarqube:
    organization: "$SONAR_ORGANIZATION"
    token:
      secure: "$SONAR_TOKEN"
    branches:
      - master
      - develop
jdk:
  - oraclejdk8
script:
  - npm test
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
