language: node_js
node_js:
  - "7"
  - "6"
dist: trusty
sudo: required
addons:
  srcclr: true
  sonarqube:
    organization: "$SONAR_ORGANIZATION"
    token:
      secure: "$SONAR_TOKEN"
    branches:
      - master
      - develop
jdk:
  - oraclejdk8
script:
  - npm test
  - sonar-scanner
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
cache:
  directories:
    - '$HOME/.sonar/cache'
