language: node_js
node_js:
  - "7"
  - "6"

dist: trusty
sudo: required

addons:
  sonarqube:
    organization: "$SONAR_ORGANIZATION"
    token:
      secure: "$SONAR_TOKEN"
    branches:
      - master
      - develop
jdk:
  - oraclejdk8
script:
  - npm test
  - cat coverage/lcov.info
  - sed -i.bak 's@^SF:/.*eslint-plugin-crc/@SF:@' coverage/lcov.info
  - cat coverage/lcov.info
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
